name: Pull Request Workflow
on: 
  - workflow_dispatch
  - pull_request
jobs:
  run_tests:
    name: Run tests on pull requests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build the image
        run: docker-compose build --compress --force-rm

      - name: Connect to container and run the tests
        run: docker-compose run --rm --user=root ms-qloud bash -c "pytest tests/unittest"
        